"""
AI-generated trade reasoning narrative.

The confidence score and trade plan itself are produced entirely by the
deterministic confluence engine (app/engine/confluence.py) -- that's the
real, auditable "AI" logic, and it never depends on this module. This
module is a genuinely optional enhancement: if ANTHROPIC_API_KEY is set,
it makes a real Claude API call to turn the computed confluence breakdown
into a clearer written explanation for the dashboard. If no key is set,
callers should just use TradePlan.reasoning (the deterministic fallback
text already generated by the engine) -- nothing here is faked or
simulated when the key is absent.
"""
from __future__ import annotations

import json

from app.core.config import get_settings
from app.engine.confluence import TradePlan

SYSTEM_PROMPT = (
    "You are a Smart Money Concepts trading analyst. You are given a "
    "structured JSON breakdown of a technical confluence score that has "
    "ALREADY been computed by a rule-based engine -- you are not "
    "generating the score or the trade levels, only writing a clear, "
    "concise (3-5 sentence) explanation of why this setup scored the way "
    "it did, in plain trading language. Always end with a one-line "
    "reminder that this is probability-based, not a guarantee. Never "
    "invent confluence factors that are not present in the JSON."
)


async def generate_narrative(plan: TradePlan, symbol: str, timeframe: str) -> str:
    settings = get_settings()
    if not settings.ANTHROPIC_API_KEY:
        return plan.reasoning

    try:
        import anthropic
    except ImportError:
        return plan.reasoning

    client = anthropic.AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)

    payload = {
        "symbol": symbol,
        "timeframe": timeframe,
        "direction": plan.direction,
        "confidence": plan.confidence,
        "entry": plan.entry,
        "stop_loss": plan.stop_loss,
        "take_profit": plan.take_profit,
        "risk_reward": plan.risk_reward,
        "confluence_factors": plan.confluence,
    }

    try:
        response = await client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=400,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": json.dumps(payload)}],
        )
        text_blocks = [block.text for block in response.content if block.type == "text"]
        narrative = "".join(text_blocks).strip()
        return narrative or plan.reasoning
    except Exception:
        # Never let a narrative-generation failure break signal generation.
        return plan.reasoning
